version: "2"
linters:
  enable:
    - copyloopvar
    - durationcheck
    - errorlint
    - exptostd
    - gocritic
    - govet
    - ineffassign
    - intrange
    - makezero
    - mirror
    - nilnesserr
    - nilnil
    - predeclared
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
  disable:
    - errcheck
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
        - ifElseChain
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    revive:
      confidence: 0.1
      rules:
        - name: argument-limit
        - name: atomic
        - name: bool-literal-in-expr
        - name: confusing-naming
        - name: constant-logical-expr
        - name: context-as-argument
        - name: defer
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: function-result-limit
        - name: get-return
        - name: increment-decrement
        - name: modifies-value-receiver
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: string-of-int
        - name: struct-tag
        - name: time-date
        - name: time-equal
        - name: unnecessary-format
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: use-any
        - name: use-fmt-print
        - name: useless-break
issues:
  max-issues-per-linter: 0  # no limit
  max-same-issues: 0        # no limit
