version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/fsnotify/fsnotify.Watcher).Close
        - (*net.TCPConn).CloseWrite
        - (*net.UnixConn).CloseWrite
        - (*os.File).Close
        - (*os.File).Write
        - (*text/tabwriter.Writer).Flush
        - (io.Closer).Close
        - (io.Writer).Write
        - (net.Conn).Close
        - (net.Listener).Close
        - fmt.Fprintf
        - fmt.Fprintln
        - io.WriteString
        - os.Setenv
        - syscall.Close
issues:
  max-issues-per-linter: 0  # no limit
  max-same-issues: 0        # no limit
